# Generated by Django 6.0.6 on 2026-06-16 12:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tobacco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('flavor', models.CharField(max_length=255, verbose_name='Flavor')),
                ('strength', models.CharField(choices=[('light', 'Light'), ('hard', 'Hard')], max_length=10, verbose_name='Strength')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='tobacco/photos/', verbose_name='Photo')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Price')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Stock quantity')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is available')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Tobacco',
                'verbose_name_plural': 'Tobaccos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Rating')),
                ('text', models.TextField(blank=True, verbose_name='Review text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('author_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('tobacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.tobacco', verbose_name='Tobacco')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
