# Generated by Django 6.0.6 on 2026-07-13 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_author_name_to_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='tobacco',
            name='health_warning_text',
            field=models.TextField(blank=True, help_text='Mandatory health warning to display on the product page, per EU TPD (2014/40/EU).', verbose_name='Health warning text'),
        ),
        migrations.AddField(
            model_name='tobacco',
            name='requires_age_verification',
            field=models.BooleanField(default=True, help_text='Should almost always be True for tobacco products sold in the EU.', verbose_name='Requires age verification'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tobacco/gallery/', verbose_name='Image')),
                ('is_main', models.BooleanField(default=False, verbose_name='Is main image')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('tobacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.tobacco', verbose_name='Tobacco')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
