# Generated by Django 6.0.6 on 2026-07-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tobacco_health_warning_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobacco',
            name='health_warning_text',
            field=models.TextField(default='Acest produs conține nicotină, care creează dependență. Fumatul dăunează grav sănătății dumneavoastră și celor din jur.', help_text='Mandatory health warning to display on the product page, per EU TPD (2014/40/EU).', verbose_name='Health warning text'),
        ),
    ]
