# Generated by Django 6.0.6 on 2026-07-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_backfill_health_warning_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tobacco',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True, verbose_name='Slug'),
        ),
    ]
