# Generated by Django 6.0.6 on 2026-07-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_backfill_currency_leu_to_ron'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookevent',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
