# Generated by Django 6.0.6 on 2026-07-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_alter_payment_amount_alter_refund_amount'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='paymentattempt',
            name='payment_att_stripe__20f614_idx',
        ),
        migrations.RenameField(
            model_name='paymentattempt',
            old_name='stripe_charge_id',
            new_name='stripe_payment_intent_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['stripe_payment_intent_id'], name='payment_att_stripe__eec25c_idx'),
        ),
    ]
