# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_remove_paymentattempt_payment_att_stripe__20f614_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webhookevent',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='webhookevent',
            name='webhook_eve_provide_2e40e6_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookevent',
            name='webhook_eve_status_330e1f_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookevent',
            name='webhook_eve_created_8fa52f_idx',
        ),
        migrations.RemoveIndex(
            model_name='webhookevent',
            name='webhook_eve_event_i_bb7559_idx',
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='webhookevent',
            name='provider',
            field=models.CharField(default='stripe', max_length=20),
        ),
    ]
